### ISSUE TITLE
Documentation on how to create new application

### ISSUE THREAD

**Issue by magic-lantern** [beeware/toga-chart#5] opened 2019-06-04 17:29 UTC
I've got the development version of Toga setup in a venv and have built toga_chart. The example app runs great with `python -m chart`. I can also create a new app of my own starting from the cookiecutter templates and including toga_chart, matplotlib, etc. but can still only get it to work using `python -m helloworld`

I cannot figure out how to create and run the application using setup.py. I want to be able to create a macOS version for testing, and then deploy it to an iOS simulator or device.

If I run `python setup.py macos -s` for example, I get the following errors and the app will not run:

```
/Users/seth/anaconda3/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_package_data'
  warnings.warn(msg)
running macos
 * Writing application template...
Template Python-macOS-template succesfully updated.
Project template: /Users/seth/.cookiecutters/Python-macOS-template
 * Determining best support package...
 * Installing support package...
Support package: https://pybee-briefcase-support.s3-us-west-2.amazonaws.com/Python-Apple-support/3.7/macOS/Python-3.7-macOS-support.b1.tar.gz
Already downloaded
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-cocoa
  Using cached https://files.pythonhosted.org/packages/6f/6b/29dbc42154ef3134b54ef366b9f1160667a9c73c2eb6f3510e72f4e3549e/toga_cocoa-0.2.15-py3-none-any.whl
Collecting rubicon-objc>=0.2.8 (from toga-cocoa)
  Using cached https://files.pythonhosted.org/packages/c7/1d/ef53fc55e035f4502a120d722d05b612830ffb0a5e923440f83bea091c7b/rubicon_objc-0.3.1-py2.py3-none-any.whl
Collecting toga-core>=0.2.15 (from toga-cocoa)
  Using cached https://files.pythonhosted.org/packages/81/4f/e79a89d856b0a5127c0438447823153052a984eeafa7ff23e0b0102a3538/toga_core-0.2.15-py3-none-any.whl
Collecting colosseum>=0.1.6 (from toga-core>=0.2.15->toga-cocoa)
  Using cached https://files.pythonhosted.org/packages/bf/3d/f7aa7fcac41f5c25a1b0a66b254cf62d4f47e0f23f2e4f314961ba922d41/colosseum-0.2.0-py3-none-any.whl
ERROR: toga-dummy 0.3.0.dev12 has requirement toga-core==0.3.0.dev12, but you'll have toga-core 0.2.15 which is incompatible.
ERROR: toga 0.3.0.dev12 has requirement toga-cocoa==0.3.0.dev12, but you'll have toga-cocoa 0.2.15 which is incompatible.
Installing collected packages: rubicon-objc, colosseum, toga-core, toga-cocoa
Successfully installed colosseum-0.2.0 rubicon-objc-0.3.1 toga-cocoa-0.2.15 toga-core-0.2.15
 * Installing project code...
Processing /Users/seth/mobile_python/beeware/toga_chart/examples
Installing collected packages: chart
  Running setup.py install for chart ... done
Successfully installed chart-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Building DMG file...
Starting Chart.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/seth/mobile_python/beeware/toga_chart/examples/macOS/Chart.app.

App started.
```

I see that the `setup.py` file references non-development versions of toga. If I update the setup.py to include toga-cocoa==0.3.0.dev12 (which is what I have installed in my venv, I get this error:

```
Collecting toga-cocoa==0.3.0.dev12
  ERROR: Could not find a version that satisfies the requirement toga-cocoa==0.3.0.dev12 (from versions: 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.3.0.dev1, 0.3.0.dev2, 0.3.0.dev3, 0.3.0.dev4, 0.3.0.dev5, 0.3.0.dev6, 0.3.0.dev7, 0.3.0.dev8, 0.3.0.dev9, 0.3.0.dev10, 0.3.0.dev11)
ERROR: No matching distribution found for toga-cocoa==0.3.0.dev12
```

How do I tell setup.py to use the current head of toga? Is that even the right question to be asking?

**Comment by freakboy3742** [comment] 2019-06-05 01:49
Definitely the right question; unfortunately, there isn't a good answer at present.

The issue is that briefcase uses "pip install" to install dependencies; and you can't pip install a development version based on a version number that isn't on PyPI.

There are a couple of possible workaround solutions:
1. Specify the toga dependencies using Github URLs. This will enable pip to install the package by downloading the package
2. Use a local DevPI instance as a proxy for PyPI. This would allow you to locally "publish" an unreleased version of Toga. However, this is a bit more overhead than most are going to be willing to use.
3. Don't use -s to start the app, ignore the error that is generated during installing dependencies, and *manually* install the packages into the app. `pip install --target <path to app_packages dir>` can be invoked on the development version to install it into the app (remember - a macOS app is acutally just a set of directories in a known layout).

There are three related briefcase issues here.

The first is beeware/briefcase#73. A "developer mode" would enable certain packages to be installed based on what is available as local checkouts.

The second has been reported in a bunch of different forms - and that is improving error handling. The log you describe on `python setup.py macos -s` contains a fatal error - but that isn't being caught and reported to the user effectively. The LSOpenURLsWithRole() is effectively macOS saying "Something broke, but I don't know what". It broke because the dependencies weren't installed. You shouldn't be able to get to that error - you should get a clear notification from briefcase that the dependency couldn't be installed.

Third: If, due to some other problem, briefcase *did* succeed- the macOS template should catch the LSOpenURLsWithRole() error. That message is effectively the "unhandled exception" error surfacing to the user - which isn't something that should ever happen, under ideal circumstances.

**Comment by magic-lantern** [comment] 2019-06-06 13:32
Thanks for the detailed explanation - this is very helpful and will likely be helpful to others. I'll give some of these options a try and report back if I find any additional issues/questions.

I think your explanation here would be a valuable addition as a new section to the existing "How to contribute to Toga" guide. What are your thoughts on documenting the above with some code and or setup.py examples?

**Comment by freakboy3742** [comment] 2019-06-07 02:17
+1 for more documentation; I'm not sure if "How to contribute to Toga" is the right place. That document is intended to get people into submitting their first PR, rather than smoothing the development process for *using* Toga. The sort of things we're talking about here are different sorts of advice.

(1) Is already an open ticket on briefcase. "How to contribute to *briefcase*" is a document that probably needs some work, and the ticket could possibly do with some more elaboration, but "here's a ticket to work on" isn't a great addition to docs, because as soon as one person fixes that ticket, the docs are out of date. However, pointing people at a Github query for good tickets to work on *would* be a good addition to docs.

(2) Would be a good addition to briefcase's docs as a "how do I package a library that isn't on PyPI" HowTo guide

(3) Is also a ticket on Briefcase (or, more specifically, [the macOS template that briefcase uses](https://github.com/beeware/Python-macOS-template). I don't think that ticket exists yet, though - it's a feature that has been in my head for a while, but I've never written down.

**Comment by proftc** [comment] 2020-08-24 06:36
Hi I am newcomer to this but I have come across a similar problem. Using Mac OS 10.14.6 and
Python 3.8.5 in a env. The standard Beeware tutorial works Fine

I created a small app using based on toga_chart as a basis and started to implement it with briefcase.
Using briefcase dev the app ran fine and created a window with the chart- great!
Then I used breifcase create

[simplechart] Generating application template...
Using app template: https://github.com/beeware/briefcase-macOS-app-template.git
Using existing template (sha 51b8367397c3b8ff7b6b193192a6367cb5163057, updated Sat Jun 20 15:06:09 2020)

[simplechart] Installing support package...
Using support package https://briefcase-support.org/python?platform=macOS&version=3.8
... using most recent revision
Python-3.8-macOS-support.b3.tar.gz already downloaded
Unpacking support package...

[simplechart] Installing dependencies...
Collecting toga-cocoa>=0.3.0.dev20
  Using cached toga_cocoa-0.3.0.dev22-py3-none-any.whl (57 kB)
Collecting rubicon-objc>=0.3.0
  Using cached rubicon_objc-0.4.0-py3-none-any.whl (53 kB)
Collecting toga-core==0.3.0.dev22
  Using cached toga_core-0.3.0.dev22-py3-none-any.whl (482 kB)
Collecting travertino>=0.1.3
  Using cached travertino-0.1.3-py3-none-any.whl (15 kB)
Installing collected packages: rubicon-objc, travertino, toga-core, toga-cocoa
Successfully installed rubicon-objc-0.4.0 toga-cocoa-0.3.0.dev22 toga-core-0.3.0.dev22 travertino-0.1.3

[simplechart] Installing application code...
Installing src/simplechart...

[simplechart] Installing application resources...
Installing src/simplechart/resources/simplechart.icns as application icon...

[simplechart] Created macOS/Simple Chart
(beeware-venv) IT036317:simplechart terry$ briefcase build

Seemed OK?
But then
(beeware-venv) IT036317:simplechart terry$   briefcase run

[simplechart] Starting app...

LSOpenURLsWithRole() failed with error -10810 for the file /Users/terry/Python/beeware-tutorial/Chart/simplechart/macOS/Simple Chart/Simple Chart.app.

I realize this is a similar error as above but any help on what to try next I would really appreaciate
Thanks

**Comment by freakboy3742** [comment] 2020-08-24 06:38
@proftc When a project runs under `dev`, but fails as a packaged app, it's almost always because of a missing dependency in your `pyproject.toml` file. Did you add `toga-chart` to the `requires` list for your app?

**Comment by proftc** [comment] 2020-08-24 09:01
Hi Russel
Brilliant it worked fine!
and thanks for your quick reply
Terry

**Comment by proftc** [comment] 2020-08-24 09:02
Brilliant it worked fine!
Thanks

**Comment by proftc** [comment] 2020-08-25 05:51
Please excuse my lack of experience here- but I was hoping to create an IOS version of my small app so I could draw a graph . I went through the instructions and got a warning of missing icons? and this warning 

warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Simple Chart editor. (in target 'Simple Chart' from project 'Simple Chart') 

Do I need to make any other steps or is Matplotlib not supported? If ot are there any other graph capabilities or will I have to write my own from scratch using the primitives available?
Thanks

**Comment by freakboy3742** [comment] 2020-08-25 06:07
Those errors don't sound like they're actually a problem - or, at least, they're not likely to be matplotlib related. The warning sounds like an Xcode development team packaging thing - entirely resolvable, just annoying. The missing icons probably aren't an issue either - more likely to be a warning than anything catastrophic. We'll need a lot more detail (like, for example, the text of the "missing icon" warnings) to provide guidance. 

However, this is now straying way off the issue being described by the original ticket; and I doubt it's even toga-chart related (more likely a briefcase issue). At the very least, we should move this part of the conversation to a new ticket (probably on the Briefcase repository so we can have an isolated discussion). You might also find it easier to jump on our [https://gitter.im/beeware/general](chat room) - it may be easier to rapidly debug if we can get/give immediate feedback.

**Comment by proftc** [comment] 2020-08-25 06:24
Hi
Thanks for the reply – I’ll start another ticket on the briefcase repository.
Thanks again for such a quick reply
Terry

**Comment by freakboy3742** [comment] 2023-07-29 03:18
I'm going to close this on the basis that Briefcase has now acquired all the missing features that this ticket was asking for. Using Toga Chart  in a new app should be as straightforward as including it in your briefcase requires list.

**Closed by freakboy3742** 2023-07-29 03:18 UTC
