### ISSUE TITLE
Can't show the plot

### ISSUE THREAD

**Issue by zwm88** [beeware/toga-chart#16] opened 2022-03-23 10:04 UTC
**Describe the bug**
Can't show the plot

**To Reproduce**
Run
python -m chart

**Expected behavior**
Show histogram plot

**Screenshots**
![image](https://user-images.githubusercontent.com/1857661/159674180-7dc943ed-a283-47c4-8221-329de141a54b.png)

![image](https://user-images.githubusercontent.com/1857661/159674248-2f4fac93-1004-4cba-9887-31d6305e3d8c.png)

**Environment:**
 - Operating System: Windows 10
 - Python version: Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21)
 - Software versions:
   - Toga: 0.3.0.dev32
   - toga-char: 0.1.0

**Additional context**

**Comment by freakboy3742** [comment] 2022-03-28 06:58
Thanks for the report! Can you provide a little more detail about the chart you were using to generate this error?

**Comment by zwm88** [comment] 2022-03-28 22:49
The chart is from the example.
By using Ubuntu + VNC I can see the chart.  Windows version is broken?  Numpy version is 1.22.3.

![image](https://user-images.githubusercontent.com/1857661/160498371-01c8e2c9-c115-4873-9c03-09b9bed2a33e.png)
![image](https://user-images.githubusercontent.com/1857661/160499540-937e8268-d8b2-4758-88d2-db03b2ca934f.png)

**Comment by saroad2** [comment] 2022-08-16 06:57
Hey, I encountered the same problem in [Eddington-GUI](https://github.com/EddLabs/eddington-gui).

The cause for this problem is happening in `Chart.draw_text`, in the [following code](https://github.com/beeware/toga-chart/blob/main/src/toga_chart/chart.py#L157).

Two fixes can be done here:
1. Make a fix in *Toga* such that it coverts everything into float when using `Canvas.translate`
2. Do the same directly in the line of the bug.

I believe that 2 is the right way to go. @freakboy3742 , what do you think?

**Comment by saroad2** [comment] 2022-08-16 08:45
After a deeper digging, the underlying problem is in pythonnet/pythonnet#1833, which will be fixed in pythonnet/pythonnet#1908.

So it seems like we only need to wait for *Pythonnet* to fix the problem on their side :)

**Comment by freakboy3742** [comment] 2022-08-16 22:10
That definitely explains the source of the problem (and why broke recently). However, #1908 is still a draft PR, so it's difficult to say when it will land. As an interim measure, it's probably desirable for us to do an explicit cast in Toga.Canvas as a workaround.

**Closed** 2022-08-16 22:42 UTC
Labels: bug
